// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Service.CatalogWrite.Persistence;

#nullable disable

namespace Service.CatalogWrite.Persistence.Migrations
{
    [DbContext(typeof(CatalogWriteDbContext))]
    [Migration("20240716111607_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog_write")
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Primitives.Entity<Service.CatalogWrite.Domain.ImageSources.ImageSourceId>", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)")
                        .HasColumnName("discriminator");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.HasKey("Id")
                        .HasName("pk_image_sources");

                    b.ToTable("image_sources", "catalog_write");

                    b.HasDiscriminator().HasValue("Entity<ImageSourceId>");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Persistence.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "catalog_write");
                });

            modelBuilder.Entity("Persistence.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.HasKey("Id", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "catalog_write");
                });

            modelBuilder.Entity("Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "catalog_write");
                });

            modelBuilder.Entity("Persistence.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.HasKey("Id", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "catalog_write");
                });

            modelBuilder.Entity("Service.CatalogWrite.Domain.Authors.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_authors");

                    b.ToTable("authors", "catalog_write");
                });

            modelBuilder.Entity("Service.CatalogWrite.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_on_utc");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_title");

                    b.ToTable("categories", "catalog_write");
                });

            modelBuilder.Entity("Service.CatalogWrite.Domain.ImageSources.ImageSource<Service.CatalogWrite.Domain.Authors.AuthorImageType>", b =>
                {
                    b.HasBaseType("Domain.Primitives.Entity<Service.CatalogWrite.Domain.ImageSources.ImageSourceId>");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("author_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Source");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Type");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_image_sources_author_id");

                    b.ToTable("image_sources", "catalog_write");

                    b.HasDiscriminator().HasValue("ImageSource<AuthorImageType>");
                });

            modelBuilder.Entity("Service.CatalogWrite.Domain.ImageSources.ImageSource<Service.CatalogWrite.Domain.Categories.CategoryImageType>", b =>
                {
                    b.HasBaseType("Domain.Primitives.Entity<Service.CatalogWrite.Domain.ImageSources.ImageSourceId>");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Source");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Type");

                    b.HasIndex("CategoryId")
                        .IsUnique()
                        .HasDatabaseName("ix_image_sources_category_id")
                        .HasFilter("[category_id] IS NOT NULL");

                    b.ToTable("image_sources", "catalog_write");

                    b.HasDiscriminator().HasValue("ImageSource<CategoryImageType>");
                });

            modelBuilder.Entity("Service.CatalogWrite.Domain.Authors.Author", b =>
                {
                    b.OwnsOne("Service.CatalogWrite.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("AuthorId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("EmailAddress")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("email_email_address");

                            b1.HasKey("AuthorId");

                            b1.HasIndex("EmailAddress")
                                .HasDatabaseName("ix_authors_email_email_address");

                            b1.ToTable("authors", "catalog_write");

                            b1.WithOwner()
                                .HasForeignKey("AuthorId")
                                .HasConstraintName("fk_authors_authors_id");
                        });

                    b.OwnsOne("Service.CatalogWrite.Domain.ValueObjects.Website", "Website", b1 =>
                        {
                            b1.Property<Guid>("AuthorId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("website_url");

                            b1.HasKey("AuthorId");

                            b1.ToTable("authors", "catalog_write");

                            b1.WithOwner()
                                .HasForeignKey("AuthorId")
                                .HasConstraintName("fk_authors_authors_id");
                        });

                    b.Navigation("Email");

                    b.Navigation("Website");
                });

            modelBuilder.Entity("Service.CatalogWrite.Domain.ImageSources.ImageSource<Service.CatalogWrite.Domain.Authors.AuthorImageType>", b =>
                {
                    b.HasOne("Service.CatalogWrite.Domain.Authors.Author", null)
                        .WithMany("Images")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_image_sources_authors_author_id");
                });

            modelBuilder.Entity("Service.CatalogWrite.Domain.ImageSources.ImageSource<Service.CatalogWrite.Domain.Categories.CategoryImageType>", b =>
                {
                    b.HasOne("Service.CatalogWrite.Domain.Categories.Category", null)
                        .WithOne("Icon")
                        .HasForeignKey("Service.CatalogWrite.Domain.ImageSources.ImageSource<Service.CatalogWrite.Domain.Categories.CategoryImageType>", "CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_image_sources_categories_category_id");
                });

            modelBuilder.Entity("Service.CatalogWrite.Domain.Authors.Author", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Service.CatalogWrite.Domain.Categories.Category", b =>
                {
                    b.Navigation("Icon")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
